<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="vijayp" ignored="0" name="Test A1" tests="3" failures="1" timestamp="02 Nov 2017 06:28:34 GMT" time="0.152" errors="0">
  <testcase name="testA1_1" time="0.058" classname="testSuiteA.TestA1">
    <skipped/>
  </testcase> <!-- testA1_1 -->
  <testcase name="testA1_2" time="0.004" classname="testSuiteA.TestA1"/>
  <testcase name="testA1_3" time="0.008" classname="testSuiteA.TestA1">
    <failure type="java.lang.AssertionError" message="failed test case ">
      <![CDATA[java.lang.AssertionError: failed test case 
	at testSuiteA.TestA1.testA1_3(TestA1.java:23)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testA1_3 -->
</testsuite> <!-- Test A1 -->
